#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# ///
"""Sync community health files from local pulp/governance repository."""

import argparse
import sys
from pathlib import Path
from textwrap import dedent
from typing import Protocol

GOVERNANCE_REPO = "pulp/governance"
HEADER_TEMPLATE = """
<!--
This file is synced from the [pulp/governance](https://github.com/pulp/governance) repository.

Do not edit this file directly: changes should be made in pulp/governance.
-->

> [!NOTE]
>
> This is a possibly outdated copy. The real document always taking precedence is here: 
> <https://github.com/pulp/governance>

"""


class ContentHandler(Protocol):
    """Processes file content during sync."""

    def __call__(self, content: str) -> str: ...


def noop_handler(content: str) -> str:
    """No-op processor that returns content unchanged."""
    return content


def security_md_handler(content: str) -> str:
    """Replace relative link in SECURITY.md with absolute link to governance repo."""
    branch = "main"
    replacement = (
        f"https://github.com/{GOVERNANCE_REPO}/blob/{branch}/"
        "docs/vulnerability-management-policy.md"
    )
    return content.replace("docs/vulnerability-management-policy.md", replacement)


class SyncManager:
    """Manages syncing of governance files from source to target repository."""

    def __init__(self, abs_governance_path: Path):
        """Initialize the sync manager.

        Args:
            abs_governance_path: Absolute path to the governance repository
        """
        self._governance_path = abs_governance_path
        self._files = {}

    def add_file(self, relative_filename: str, handler: ContentHandler | None = None):
        """Register a file to be synced.

        Args:
            relative_filename: Relative path to the file in the governance repo
            handler: Optional handler function to process file content.
        """
        if handler is None:
            handler = noop_handler
        self._files[relative_filename] = handler

    def run(self, abs_target: Path):
        """Execute the sync operation.

        Args:
            abs_target: Absolute path to the target repository root
        """
        print(f"Governance repository: {self._governance_path}")
        print(f"Target repository: {abs_target}")
        print()

        for filename, handler in self._files.items():
            print(f"Syncing {filename}...", end=" ")
            try:
                content = self._read_local_file(filename)
                content = handler(content)
                target_path = abs_target / filename
                final_content = self._inject_header(filename) + content
                target_path.write_text(final_content)
            except FileNotFoundError as e:
                print(f"✗ File not found: {e}")
                sys.exit(1)
            except Exception as e:
                print(f"✗ Failed: {e}")
                sys.exit(1)
            print("✓")

        print()
        print("All files synced successfully!")

    def _inject_header(self, filename: str) -> str:
        """Inject a header comment for synced files."""
        source_file = self._governance_path / filename
        return dedent(HEADER_TEMPLATE).format(
            source_file=source_file,
            governance_repo=GOVERNANCE_REPO,
        )

    def _read_local_file(self, filename: str) -> str:
        """Read a file from the local governance repository."""
        file_path = self._governance_path / filename
        if not file_path.exists():
            raise FileNotFoundError(f"File not found: {file_path}")
        return file_path.read_text()


def validate_directory(path: Path, label: str) -> None:
    """Validate that a path exists and is a directory."""
    if not path.exists():
        print(f"Error: {label} not found: {path}")
        sys.exit(1)

    if not path.is_dir():
        print(f"Error: Not a directory: {path}")
        sys.exit(1)


def parse_args() -> tuple[Path, Path]:
    """Parse and validate command line arguments.

    Returns:
        Tuple of (governance_path, target_path) as absolute paths
    """
    parser = argparse.ArgumentParser(
        description="Sync community health files from local pulp/governance repository"
    )
    parser.add_argument(
        "governance_path",
        type=Path,
        help="Path to local pulp/governance repository",
    )
    parser.add_argument(
        "target_path",
        type=Path,
        help="Path to target repository root",
    )

    args = parser.parse_args()
    governance_path = args.governance_path.resolve()
    target_path = args.target_path.resolve()

    validate_directory(governance_path, "Governance repository")
    validate_directory(target_path, "Target repository")

    return governance_path, target_path


def main() -> None:
    """Main entry point."""
    governance_path, target_path = parse_args()
    manager = SyncManager(governance_path)
    manager.add_file("SECURITY.md", security_md_handler)
    manager.add_file("CODE_OF_CONDUCT.md")
    manager.add_file("CONTRIBUTING.md")
    manager.run(target_path)


if __name__ == "__main__":
    main()
